### ISSUE TITLE
Typo in GHA CI

### ISSUE THREAD

**Issue by phinate** [scikit-hep/cookie#24]
Here, it should be `pipx` and not `pip`:

https://github.com/scikit-hep/cookie/blob/90bcf03266b1144b36400a5981c3a2d2f249e5f0/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L71

My fork has diverged a bit so probably easier to just patch this from your side :)

Also -- why is `CONTRIBUTING.md` in `.github/` and not the root folder of the project?

**Comment by phinate** [comment]
also, thanks for this, it's been v helpful for setting up new projects! I find the `flake8-bugbear` to be a bit pedantic for no reason (B008, B009 in particular), but that's why forks exist ;)

**Comment by henryiii** [comment]
PS: While I don't think bugbear understands this, if you have a type checked codebase, this is probably safe:

```python
def something(x: Final[list[int]] = []) -> Any: ...
```

MyPy will not allow you to change `x`, so it's the equivalent of setting a non-mutable argument here, which is fine. As long as you always run MyPy, and don't have `type: ignores`, etc - violating this won't be caught at runtime.

**Comment by phinate** [comment]
thanks for the explanation! yeah in my use-case the default value of `dict()` leads to a non-op (it just needs to be able to be unpacked with `**`), but I understand the general case better now, thanks!
