### ISSUE TITLE
Duplication of flake8 config in pyproject.toml and .flake8

### ISSUE THREAD

**Issue by phinate** [scikit-hep/cookie#58]
Just wondering if it's intentional to have two sets of flake8 options, one in `.flake8` and one in `pyproject.toml`?

There is some subtle difference between them :)

**Comment by henryiii** [comment]
There can't be any flake8 config in pyproject.toml, flake8 doesn't support it.

**Comment by henryiii** [comment]
Ahh, maybe you mean setup.cfg and .flake8. Hmm, we probably don't delete the .flake8 file if it uses a setuptools backend. We could keep only the flake8 file, or we could make sure it gets deleted when using setuptools or pybind11 backends.

**Comment by phinate** [comment]
ah indeed I meant `setup.cfg`, sorry for the confusion!

Deleting`.flake8` for the setuptools/pybind11 builds in favour of `setup.cfg` would be my preference! Just ran into this when modifying it, but having pre-commit throw errors since `.flake8` overrides it :)

**Comment by henryiii** [comment]
Yeah, that's what was originally intended. I can either hack it to delete the file, or come up with a syntax for naming a file that excludes builds instead of includes them. (Currently I'd have to list all six other backends in the file name).
