### ISSUE TITLE
Pre-commit on PRs

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/cookie#7]
I think this needs `--all-files` in https://github.com/scikit-hep/cookie/blob/ccba61982ea04cae0e2eefae47a86d28d73e3e55/%7B%7Bcookiecutter.project_name%7D%7D/.github/workflows/ci.yml#L24

Or perhaps something that diffs the PR branch against the head branch.

**Comment by henryiii** [comment]
Yes, I believe you are right. Setting the args removes the "all-args" default.
